anchor_version="0.24.2"

[features]
seeds = false

[workspace]
members = [
  "programs/snowflake",
  "snow-util"
]

[programs.localnet]
snowflake = "E4dX4XEtJTRxAX8DoN3qhdvEbixKD71KFx9S4fHmrAKB"

[programs.mainnet]
snowflake = "E4dX4XEtJTRxAX8DoN3qhdvEbixKD71KFx9S4fHmrAKB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./keypairs/admin.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.spec.ts"
snowflake = "yarn run ts-mocha -t 1000000 tests/snowflake.spec.ts"
