anchor_version="0.24.2"

[features]
seeds = false

[workspace]
members = [
  "programs/snowflake",
  "snow-util"
]

[programs.localnet]
snowflake = "HAD4YK6z3mFEYaFd82Ln2aVTUp3rt1ifXBHbFLfoot83"

[programs.mainnet]
snowflake = "HAD4YK6z3mFEYaFd82Ln2aVTUp3rt1ifXBHbFLfoot83"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -t 1000000 tests/**/*.spec.ts"
